/**
 * ═══════════════════════════════════════════════
 *  REWAN TECH SOLUTIONS — Centralized Config
 *  Update all business details here globally.
 * ═══════════════════════════════════════════════
 */

export const SITE = {
  name: 'Rewan Tech Solutions',
  tagline: 'Premium IT Engineering Partner',
  description:
    'Premium IT engineering partner. Web, Mobile, AI, Cloud. Fixed-price contracts. Extraordinary results.',
  url: 'https://rewantechsolutions.com',
  logo: '/logo.svg',
  favicon: '/favicon.ico',
};

export const CONTACT = {
  email: 'rewantechsolutions@gmail.com',
  phone: '+91 8545098444',
  phoneRaw: '+918545098444',
  whatsapp: '+91 8545098444',
  whatsappRaw: '918545098444',
  whatsappRaw2: '918545098444', // secondary WhatsApp
  formspreeEndpoint: 'https://formspree.io/f/meeprbqd',
};

export const SOCIAL = {
  instagram: 'https://instagram.com/rewantechsolutions',
  whatsapp: `https://wa.me/${CONTACT.whatsappRaw}?text=Hi%2C+I+want+to+discuss+a+project`,
  whatsapp2: `https://wa.me/${CONTACT.whatsappRaw2}?text=Hi%2C+I+want+to+discuss+a+project`,
};

export const SEO = {
  defaultTitle: 'Rewan Tech Solutions — Premium IT Engineering Partner',
  titleTemplate: '%s — Rewan Tech Solutions',
  description: SITE.description,
  
  og: {
    type: 'website',
    image: '/og-image.png',
    imageWidth: 1200,
    imageHeight: 630,
  },
  twitter: {
    card: 'summary_large_image',
    site: '@rewantechsol',
  },
  keywords:[
  'rewan tech solutions',
  'rewan tech',
  'rewan tech solutions india',
  'rewan tech solutions company',
  'rewan tech solutions website',
    'IT company in Jhansi',
  'best IT company in Jhansi',
  'top IT company in Jhansi',
  'software company in Jhansi',
  'web development company in Jhansi',
  'app development company in Jhansi',
  'website developer Jhansi',
  'best website development company Jhansi',
  'mobile app developer Jhansi',
  'software developer Jhansi',
  'digital marketing company Jhansi',
  'startup IT company Jhansi',
  'custom software company Jhansi',
  'Jhansi IT services company',
  'Jhansi tech company',
  'Jhansi software solutions',
  'Jhansi web design company',
  'Jhansi app development services',
  'Jhansi digital agency',
  'Jhansi website designer',
   'rewan tech Jhansi',
  'rewan tech solutions Jhansi',
  'rewan IT company Jhansi',
  'best IT company Jhansi rewan tech',
  'top IT company Jhansi rewan tech',
  'rewan software company Jhansi',
  'rewan web development Jhansi',
  'rewan app development Jhansi',
  'rewan tech services Jhansi',
  'rewan digital agency Jhansi',
  'rewan tech website Jhansi',
  'Jhansi best IT company rewan tech solutions',
  'rewan tech near me Jhansi',
  'rewan tech company near Jhansi',
  'rewan tech contact Jhansi',
  'rewan tech office Jhansi',
  'rewan IT services Jhansi',
  'rewan tech solutions Uttar Pradesh',
  'rewan software company UP',
  'rewan tech UP company',
   'rewan tech Jhansi',
  'rewan tech solutions Jhansi',
  'rewan IT company Jhansi',
  'best IT company Jhansi rewan tech',
  'top IT company Jhansi rewan tech',
  'rewan software company Jhansi',
  'rewan web development Jhansi',
  'rewan app development Jhansi',
  'rewan tech services Jhansi',
  'rewan digital agency Jhansi',
  'rewan tech website Jhansi',
  'Jhansi best IT company rewan tech solutions',
  'rewan tech near me Jhansi',
  'rewan tech company near Jhansi',
  'rewan tech contact Jhansi',
  'rewan tech office Jhansi',
  'rewan IT services Jhansi',
  'rewan tech solutions Uttar Pradesh',
  'rewan software company UP',
  'rewan tech UP company',
   'IT company in Uttar Pradesh',
  'best IT company in UP',
  'software company Uttar Pradesh',
  'web development company UP',
  'app development company UP',
  'top software company UP',
  'custom software development UP',
  'website development company Uttar Pradesh',
  'mobile app development UP',
  'digital agency Uttar Pradesh',
  'startup IT company UP',
  'IT services Uttar Pradesh',
  'technology company UP',
  'best developers in Uttar Pradesh',
  'UP web design company',
  'UP app developers',
  'UP software solutions company',
  'UP tech startup company',
  'UP IT solutions provider',
  'IT company near me Uttar Pradesh',
   'IT company in Gwalior',
  'best IT company in Gwalior',
  'software company in Gwalior',
  'web development company Gwalior',
  'app development company Gwalior',
  'website developer Gwalior',
  'mobile app developer Gwalior',
  'software developer Gwalior',
  'digital agency Gwalior',
  'startup IT company Gwalior',
  'custom software company Gwalior',
  'Gwalior web design company',
  'Gwalior app development services',
  'Gwalior software solutions',
  'technology company Gwalior',
  'Gwalior IT services',
  'best developers in Gwalior',
  'top IT company Gwalior',
  'Gwalior tech company',
  'IT company near me Gwalior',
   'rewan tech Gwalior',
  'rewan IT company Gwalior',
  'rewan tech solutions Gwalior',
  'best IT company Gwalior rewan tech',
  'top IT company Gwalior rewan',
  'rewan web development Gwalior',
  'rewan app development Gwalior',
  'rewan software company Gwalior',
  'rewan tech services Gwalior',
  'rewan digital agency Gwalior',
  'best IT company near me',
  'website developer near me',
  'app developer near me',
  'software company near me',
  'IT services near me',
  'web development near me',
  'app development near me',
  'digital agency near me',
  'startup IT partner near me',
  'custom software near me',
  'it company india',
  'software company india',
  'software development company india',
  'top software company india',
  'best software company india',
  'digital product development company',
  'custom software development company',
  'modern software development company',
  'premium software development company',
  'technology solutions company',
  'business technology partner',
  'digital transformation company',
  'full service IT company',
  'web and app development company',
  'IT services company india',

  'web development company',
  'website development company',
  'custom website development',
  'professional website development',
  'business website development',
  'responsive website development',
  'corporate website development',
  'startup website development',
  'enterprise website development',
  'website design and development company',
  'web development services',
  'website development services',
  'custom web development services',
  'full stack web development company',
  'frontend development company',
  'backend development company',
  'website redesign services',
  'website maintenance services',
  'website optimization services',
  'modern website development company',

  'web development company india',
  'website development company india',
  'custom website development india',
  'responsive web development india',
  'business website development india',
  'corporate website design india',
  'startup website development india',
  'enterprise website development india',
  'frontend development company india',
  'backend development company india',
  'web design company india',
  'professional web development india',
  'affordable web development india',
  'best web development company india',
  'top web development agency india',
  'website development agency india',
  'B2B website development india',
  'SEO friendly website development india',
  'landing page development india',
  'portfolio website development india',

  'mobile app development company',
  'mobile app development services',
  'custom mobile app development',
  'android app development company',
  'ios app development company',
  'cross platform app development',
  'hybrid app development company',
  'business app development company',
  'startup app development company',
  'enterprise mobile app development',
  'mobile application development company',
  'mobile application development services',
  'app design and development company',
  'custom app development company',
  'scalable mobile app development',
  'mobile app development agency',
  'UI UX mobile app development',
  'react native app development company',
  'flutter app development company',
  'on demand app development company',

  'mobile app development company india',
  'mobile app development india',
  'android app development india',
  'ios app development india',
  'custom app development india',
  'react native app development india',
  'flutter app development india',
  'cross platform app development india',
  'hybrid app development india',
  'mobile software development india',
  'business app development india',
  'startup app development india',
  'enterprise app development india',
  'mobile app design company india',
  'best mobile app development company india',
  'top app development company india',
  'affordable app development company india',
  'custom android app development india',
  'custom ios app development india',
  'app development agency india',

  'AI integration services',
  'AI development company',
  'artificial intelligence development company',
  'AI software development',
  'AI application development',
  'AI powered solutions',
  'AI automation services',
  'AI chatbot development',
  'AI assistant development',
  'AI business solutions',
  'AI product development',
  'machine learning development services',
  'machine learning solutions company',
  'ML integration services',
  'AI ML integration company',
  'predictive analytics solutions',
  'generative AI development company',
  'LLM integration services',
  'AI workflow automation',
  'intelligent automation company',

  'AI development company india',
  'AI integration company india',
  'machine learning company india',
  'AI chatbot development india',
  'LLM integration company india',
  'generative AI company india',
  'AI automation services india',
  'artificial intelligence company india',
  'ML development company india',
  'AI software development india',
  'AI application development india',
  'business AI solutions india',
  'predictive analytics company india',
  'AI consulting company india',
  'custom AI solutions india',
  'custom ML solutions india',
  'AI SaaS development india',
  'AI tool development india',
  'AI agent development india',
  'AI based software development india',

  'cloud services company',
  'cloud consulting services',
  'cloud infrastructure services',
  'cloud deployment services',
  'cloud migration services',
  'cloud app development',
  'cloud solutions provider',
  'cloud engineering company',
  'cloud operations company',
  'DevOps services company',
  'DevOps consulting company',
  'CI CD implementation services',
  'infrastructure automation services',
  'cloud DevOps company',
  'AWS development company',
  'Azure development company',
  'Google Cloud development company',
  'Kubernetes services company',
  'docker containerization services',
  'server deployment services',

  'cloud services company india',
  'DevOps company india',
  'cloud consulting india',
  'cloud migration company india',
  'AWS services india',
  'Azure services india',
  'Google Cloud services india',
  'CI CD services india',
  'DevOps consulting india',
  'cloud engineering india',
  'infrastructure automation india',
  'Kubernetes company india',
  'Docker services india',
  'cloud deployment india',
  'cloud app hosting india',
  'scalable cloud solutions india',
  'startup cloud solutions india',
  'enterprise cloud services india',
  'managed cloud services india',
  'cloud architecture company india',

  'UI UX design company',
  'UI UX design services',
  'UI design company',
  'UX design company',
  'product design company',
  'web UI UX design',
  'mobile app UI UX design',
  'dashboard UI UX design',
  'SaaS UI UX design company',
  'user experience design services',
  'user interface design services',
  'website UI design services',
  'app UX design services',
  'wireframe design services',
  'prototype design company',
  'design system services',
  'conversion focused UI UX design',
  'modern product design services',
  'landing page UI UX design',
  'branding and UI UX design',

  'UI UX design company india',
  'UI UX design services india',
  'web UI UX design india',
  'mobile app UI UX design india',
  'product design company india',
  'UX design agency india',
  'UI design agency india',
  'SaaS design company india',
  'dashboard design company india',
  'website redesign company india',
  'landing page design company india',
  'prototype design india',
  'wireframe design india',
  'app interface design india',
  'user experience design india',
  'user interface design india',
  'conversion focused design india',
  'startup UI UX agency india',
  'enterprise product design india',
  'best UI UX company india',

  'ecommerce development company',
  'ecommerce website development',
  'custom ecommerce development',
  'online store development company',
  'shopping website development',
  'ecommerce app development',
  'B2B ecommerce development',
  'B2C ecommerce development',
  'Shopify development company',
  'WooCommerce development company',
  'custom checkout development',
  'payment gateway integration',
  'multi vendor ecommerce development',
  'ecommerce UI UX design',
  'ecommerce maintenance services',
  'ecommerce platform development',
  'scalable ecommerce solutions',
  'marketplace development company',
  'product catalog website development',
  'online store optimization services',

  'ecommerce development company india',
  'ecommerce website development india',
  'online store development india',
  'Shopify development india',
  'WooCommerce development india',
  'custom ecommerce development india',
  'marketplace development india',
  'B2B ecommerce company india',
  'B2C ecommerce company india',
  'ecommerce app development india',
  'payment gateway integration india',
  'shopping website development india',
  'multi vendor ecommerce india',
  'ecommerce UI UX design india',
  'startup ecommerce development india',
  'enterprise ecommerce development india',
  'custom online store india',
  'best ecommerce company india',
  'top ecommerce developers india',
  'ecommerce agency india',

  'Next.js development company',
  'Next.js development services',
  'Next.js website development',
  'Next.js web app development',
  'Next.js developers',
  'Next.js app development company',
  'Next.js frontend development',
  'Next.js full stack development',
  'Next.js landing page development',
  'Next.js SaaS development',
  'Next.js enterprise development',
  'Next.js maintenance services',
  'Next.js migration services',
  'Next.js optimization services',
  'SSR development services',
  'static website development Next.js',
  'performance focused Next.js development',
  'SEO friendly Next.js development',
  'custom Next.js project development',
  'hire Next.js developers',

  'Next.js development company india',
  'Next.js developers india',
  'Next.js development india',
  'Next.js website development india',
  'Next.js web app development india',
  'hire Next.js developers india',
  'custom Next.js development india',
  'Next.js migration india',
  'Next.js agency india',
  'best Next.js development company india',
  'top Next.js developers india',
  'SEO friendly Next.js website india',
  'SSR development company india',
  'Next.js startup development india',
  'Next.js enterprise solutions india',
  'Next.js landing page agency india',
  'Next.js SaaS development india',
  'performance website development india',
  'fast loading website development india',
  'modern frontend company india',

  'React development company',
  'React development services',
  'React web development',
  'React application development',
  'React frontend development',
  'React JS development company',
  'React app development services',
  'custom React development',
  'React dashboard development',
  'React SaaS development',
  'React enterprise app development',
  'React migration services',
  'React maintenance services',
  'React UI development',
  'component based frontend development',
  'single page application development',
  'SPA development company',
  'React product development',
  'hire React developers',
  'scalable React development company',

  'React development company india',
  'React development india',
  'React JS development india',
  'React web development india',
  'React app development india',
  'hire React developers india',
  'custom React development india',
  'React frontend company india',
  'React dashboard development india',
  'SPA development india',
  'best React development company india',
  'top React developers india',
  'React agency india',
  'React product development india',
  'React startup development india',
  'React enterprise development india',
  'React UI development india',
  'modern React website company india',
  'React website redesign india',
  'fast React app development india',

  'software development services',
  'custom software development',
  'business software development',
  'enterprise software development',
  'SaaS development company',
  'B2B software development company',
  'custom CRM development',
  'custom ERP development',
  'internal tools development',
  'workflow automation software',
  'business process automation software',
  'software consulting company',
  'software product development',
  'digital solutions company',
  'technology consulting company',
  'custom portal development',
  'admin dashboard development',
  'client portal development',
  'web application development services',
  'custom business applications',

  'software development company india',
  'custom software development india',
  'enterprise software development india',
  'SaaS development company india',
  'business software development india',
  'software consulting india',
  'custom CRM development india',
  'custom ERP development india',
  'internal tools development india',
  'workflow automation company india',
  'web application development india',
  'business application development india',
  'digital transformation services india',
  'technology consulting india',
  'software product development india',
  'B2B software company india',
  'startup software company india',
  'enterprise IT solutions india',
  'custom portal development india',
  'admin dashboard development india',

  'startup tech partner',
  'startup development company',
  'MVP development company',
  'minimum viable product development',
  'startup product development',
  'startup website development',
  'startup app development',
  'launch ready software development',
  'product engineering company',
  'prototype to product development',
  'agile software development company',
  'rapid application development company',
  'startup software agency',
  'product launch development company',
  'technical partner for startups',
  'MVP development company india',
  'startup tech partner india',
  'startup app development india',
  'startup website development india',
  'product engineering company india',

  'small business website development',
  'small business app development',
  'business automation services',
  'digital solutions for small business',
  'IT services for startups',
  'IT services for businesses',
  'website development for doctors',
  'website development for lawyers',
  'website development for schools',
  'website development for coaching institutes',
  'website development for restaurants',
  'website development for real estate',
  'website development for ecommerce brands',
  'website development for agencies',
  'website development for consultants',
  'software solutions for clinics',
  'software solutions for education',
  'software solutions for retail',
  'software solutions for logistics',
  'software solutions for service businesses',

  'website development in agra',
  'website development in delhi',
  'website development in noida',
  'website development in gurgaon',
  'website development in ghaziabad',
  'website development in lucknow',
  'website development in kanpur',
  'website development in jaipur',
  'website development in indore',
  'website development in bhopal',
  'website development in mumbai',
  'website development in pune',
  'website development in bangalore',
  'website development in hyderabad',
  'website development in chennai',
  'website development in ahmedabad',
  'website development in surat',
  'website development in patna',
  'website development in varanasi',
  'website development in nagpur',

  'app development in agra',
  'app development in delhi',
  'app development in noida',
  'app development in gurgaon',
  'app development in lucknow',
  'app development in jaipur',
  'app development in indore',
  'app development in bhopal',
  'app development in mumbai',
  'app development in pune',
  'app development in bangalore',
  'app development in hyderabad',
  'app development in chennai',
  'app development in ahmedabad',
  'app development in surat',
  'app development in patna',
  'app development in kanpur',
  'app development in varanasi',
  'app development in nagpur',
  'app development in india',

  'web development agency for startups',
  'web development company for small business',
  'best web development company for startups',
  'affordable website development for business',
  'high quality website development company',
  'premium website design agency',
  'premium IT company india',
  'premium digital product agency',
  'modern web agency india',
  'creative technology agency',
  'results driven software company',
  'performance focused development agency',
  'SEO friendly website company',
  'conversion focused website development',
  'fast loading website development company',
  'brand focused web development',
  'custom business website company',
  'lead generation website development',
  'service business website development',
  'high converting landing page agency',

  'hire web developers india',
  'hire app developers india',
  'hire React developers',
  'hire Next.js developers',
  'hire frontend developers india',
  'hire backend developers india',
  'hire mobile app developers india',
  'hire UI UX designers india',
  'hire software development company',
  'hire ecommerce developers india',
  'hire SaaS developers india',
  'hire dedicated developers india',
  'outsource web development india',
  'outsource app development india',
  'outsource software development india',
  'dedicated development team india',
  'remote development team india',
  'offshore development company india',
  'development partner india',
  'technology outsourcing company india',

  'best IT company in india',
  'best web development company in india',
  'best mobile app development company in india',
  'best software company in india',
  'top website development company india',
  'top app development agency india',
  'top software development company india',
  'top React development company india',
  'top Next.js development company india',
  'top ecommerce development company india',
  'best UI UX design company india',
  'best DevOps company india',
  'top AI development company india',
  'best startup tech company india',
  'best custom software development company india',
  'trusted software company india',
  'reliable IT company india',
  'expert web developers india',
  'professional software agency india',
  'experienced development team india',

  'custom website development company for business',
  'custom software development for startups',
  'mobile app development for startups',
  'Next.js website development company india',
  'React application development company india',
  'UI UX design and development company',
  'AI chatbot development company india',
  'cloud and DevOps services company india',
  'ecommerce website design and development company',
  'SEO friendly business website development',
  'fast and modern website development company',
  'full stack software development company india',
  'custom admin panel development company',
  'business automation software development company',
  'web app development company for startups',
  'custom internal tools development company',
  'digital product design and development company',
  'scalable SaaS development company india',
  'custom dashboard development services',
  'website redesign and optimization company'
]
};

